version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:Cbi2009$$@host.docker.internal:5432/employeeaccesshub
      - SESSION_SECRET=use-a-strong-secret-key-here
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
networks:
  app-network:
    driver: bridge


